### ISSUE TITLE
Version mismatch error

### ISSUE THREAD

**Issue by Ola131v** [eske/seq2seq#10]
Hello!
I'm using Tensorflow version 1.2.1 python3.5 and I am trying to train speech-to-text model. 
As API used in the code was earlier than Tensorflow v.1.0, i used tf_upgrade.py script and some minor manual updates, but still I get the error while running the code:
Traceback (most recent call last):
  File "/usr/python354/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/python354/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/olgastrizhko/cuda-workspace/seq2seq-speech_sh/translate/__main__.py", line 225, in <module>
    main()
  File "/home/olgastrizhko/cuda-workspace/seq2seq-speech_sh/translate/__main__.py", line 177, in main
    model = MultiTaskModel(name='main', checkpoint_dir=checkpoint_dir, decode_only=decode_only, **config)
  File "/home/olgastrizhko/cuda-workspace/seq2seq-speech_sh/translate/multitask_model.py", line 24, in __init__
    model = TranslationModel(checkpoint_dir=None, keep_best=keep_best, **kwargs_)
  File "/home/olgastrizhko/cuda-workspace/seq2seq-speech_sh/translate/translation_model.py", line 119, in __init__
    **kwargs)
  File "/home/olgastrizhko/cuda-workspace/seq2seq-speech_sh/translate/seq2seq_model.py", line 134, in __init__
    decoder_input_length=self.decoder_input_length, **parameters
  File "/home/olgastrizhko/cuda-workspace/seq2seq-speech_sh/translate/decoders.py", line 408, in attention_decoder
    swap_memory=decoder.swap_memory)
  File "/usr/python354/lib/python3.5/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2770, in while_loop
    result = context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "/usr/python354/lib/python3.5/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2599, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/usr/python354/lib/python3.5/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2549, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/home/olgastrizhko/cuda-workspace/seq2seq-speech_sh/translate/decoders.py", line 395, in _time_step
    new_attns, new_attn_weights = attention_(new_state, prev_weights=attn_weights)
  File "/home/olgastrizhko/cuda-workspace/seq2seq-speech_sh/translate/decoders.py", line 253, in multi_attention
    for weights_, hidden, encoder in zip(prev_weights, hidden_states, encoders)]))
  File "/home/olgastrizhko/cuda-workspace/seq2seq-speech_sh/translate/decoders.py", line 253, in <listcomp>
    for weights_, hidden, encoder in zip(prev_weights, hidden_states, encoders)]))
  File "/home/olgastrizhko/cuda-workspace/seq2seq-speech_sh/translate/decoders.py", line 244, in attention
    return attention_(state, prev_weights, hidden_states, encoder, **kwargs)
  File "/home/olgastrizhko/cuda-workspace/seq2seq-speech_sh/translate/decoders.py", line 175, in global_attention
    attention_filter_length=encoder.attention_filter_length
  File "/home/olgastrizhko/cuda-workspace/seq2seq-speech_sh/translate/decoders.py", line 122, in compute_energy
    y = linear_unsafe(state, attn_size, True, tf.variable_scope(name))
  File "/home/olgastrizhko/cuda-workspace/seq2seq-speech_sh/translate/rnn.py", line 125, in fun_
    return fun(*args, **kwargs)
  File "/usr/python354/lib/python3.5/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 1031, in _linear
    initializer=bias_initializer)
  File "/usr/python354/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 1065, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/usr/python354/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 962, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/usr/python354/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 367, in get_variable
    validate_shape=validate_shape, use_resource=use_resource)
  File "/usr/python354/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 352, in _true_getter
    use_resource=use_resource)
  File "/usr/python354/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 725, in _get_single_variable
    validate_shape=validate_shape)
  File "/usr/python354/lib/python3.5/site-packages/tensorflow/python/ops/variables.py", line 200, in __init__
    expected_shape=expected_shape)
  File "/usr/python354/lib/python3.5/site-packages/tensorflow/python/ops/variables.py", line 278, in _init_from_args
    initial_value(), name="initial_value", dtype=dtype)
  File "/usr/python354/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 701, in <lambda>
    shape.as_list(), dtype=dtype, partition_info=partition_info)
TypeError: __call__() got an unexpected keyword argument 'dtype'
=========================================
When a parameter "scope='....' " was there previously, the error message was following:
Traceback (most recent call last):
  File "/usr/python354/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/python354/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/olgastrizhko/cuda-workspace/seq2seq-speech_test/translate/__main__.py", line 225, in <module>
    main()
  File "/home/olgastrizhko/cuda-workspace/seq2seq-speech_test/translate/__main__.py", line 177, in main
    model = MultiTaskModel(name='main', checkpoint_dir=checkpoint_dir, decode_only=decode_only, **config)
  File "/home/olgastrizhko/cuda-workspace/seq2seq-speech_test/translate/multitask_model.py", line 26, in __init__
    model = TranslationModel(checkpoint_dir=None, keep_best=keep_best, **kwargs_)
  File "/home/olgastrizhko/cuda-workspace/seq2seq-speech_test/translate/translation_model.py", line 118, in __init__
    **kwargs)
  File "/home/olgastrizhko/cuda-workspace/seq2seq-speech_test/translate/seq2seq_model.py", line 139, in __init__
    **parameters
  File "/home/olgastrizhko/cuda-workspace/seq2seq-speech_test/translate/decoders.py", line 472, in beam_search_decoder
    linear_unsafe(initial_state, cell.state_size, False, scope='initial_state_projection')
  File "/home/olgastrizhko/cuda-workspace/seq2seq-speech_test/translate/rnn.py", line 131, in fun_
    return fun(*args, **kwargs)
TypeError: _linear() got an unexpected keyword argument 'scope'

Could you please help me to solve this issue
Thank you in advance! Looking forward to hear from you.
Best Regards, 
Olga.

**Comment by eske** [comment]
Hello Olga,

It seems like you're using a very old version of the code.
You should get the latest version (on branch master), which is compatible
with TensorFlow 1.2+.

Alexandre
